"""Add salary_min and salary_max columns to job_listings

Revision ID: 4c82fad6a67d
Revises: eee2a9894972
Create Date: 2025-11-05 19:36:52.234993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c82fad6a67d'
down_revision = 'eee2a9894972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_min', sa.Integer(), nullable=True, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('salary_max', sa.Integer(), nullable=True, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_min')

    # ### end Alembic commands ###
