"""Add notifications table

Revision ID: 6819ef0a1309
Revises: 9e522d39eb64
Create Date: 2025-10-28 10:04:31.548068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6819ef0a1309'
down_revision = '9e522d39eb64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('job_posted', 'application_received', 'application_status'), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_id_user'))
        batch_op.drop_constraint(batch_op.f('applicants_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_user'], ['id_user'])

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_id_applicant'))
        batch_op.drop_index(batch_op.f('idx_id_job'))
        batch_op.drop_constraint(batch_op.f('applications_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('applications_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'applicants', ['id_applicant'], ['id_applicant'])
        batch_op.create_foreign_key(None, 'job_listings', ['id_job'], ['id_job'])

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_id_user'))
        batch_op.drop_constraint(batch_op.f('companies_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_user'], ['id_user'])

    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_id_company'))
        batch_op.drop_constraint(batch_op.f('job_listings_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['id_company'], ['id_company'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('job_listings_ibfk_1'), 'companies', ['id_company'], ['id_company'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_id_company'), ['id_company'], unique=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('companies_ibfk_1'), 'users', ['id_user'], ['id_user'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_id_user'), ['id_user'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('applications_ibfk_2'), 'job_listings', ['id_job'], ['id_job'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('applications_ibfk_1'), 'applicants', ['id_applicant'], ['id_applicant'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_id_job'), ['id_job'], unique=False)
        batch_op.create_index(batch_op.f('idx_id_applicant'), ['id_applicant'], unique=False)

    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('applicants_ibfk_1'), 'users', ['id_user'], ['id_user'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_id_user'), ['id_user'], unique=False)

    op.drop_table('notifications')
    # ### end Alembic commands ###
