"""Add is_open column to job_listings for closing jobs

Revision ID: eee2a9894972
Revises: 6819ef0a1309
Create Date: 2025-10-28 23:51:32.060403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eee2a9894972'
down_revision = '6819ef0a1309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # KODE PENTING: Menambahkan kolom 'is_open' ke job_listings
    # Kami menggunakan server_default=sa.text('true') untuk memastikan
    # semua lowongan kerja yang sudah ada secara otomatis diatur sebagai 'Open' (True).
    op.add_column('job_listings', sa.Column('is_open', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    
    # KODE UNTUK USERS: Perubahan tipe ENUM (Jika ada) - Kami biarkan karena ini adalah sinkronisasi skema.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'applicant', 'company'),
               type_=sa.Enum('applicant', 'company', 'admin'),
               existing_nullable=False)

    # Catatan: Semua kode yang menyebabkan konflik pada tabel applicants, applications,
    # dan companies telah DIHAPUS karena tidak relevan dengan migrasi ini.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # KODE UNTUK USERS: Kembalikan tipe ENUM (Jika ada)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('applicant', 'company', 'admin'),
               type_=mysql.ENUM('admin', 'applicant', 'company'),
               existing_nullable=False)

    # KODE PENTING: Menghapus kolom 'is_open'
    op.drop_column('job_listings', 'is_open')

    # ### end Alembic commands ###